name = "revelytics-final"
main = "src/worker.ts"
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB"
database_name = "revlytics-db"
database_id = "939a2da3-3705-413d-a89f-dd10e1e08335"

[vars]
ENVIRONMENT = "production"
API_URL = "https://revelytics-final.mkmkataria07.workers.dev"

[assets]
directory = "./dist"
binding = "ASSETS"